#! /usr/bin/env python3
if __name__ == "__main__":
    import os
    path = os.path.abspath(os.path.dirname(__file__))

    import sys
    sys.path.append(path)

    import runpy
    runpy.run_module("bemani.utils.twodxutils", run_name="__main__")