#! /usr/bin/env python3
import os
path = os.path.abspath(os.path.dirname(__file__))
name = os.path.basename(__file__)

import sys
sys.path.append(path)

import runpy
runpy.run_module(f"bemani.utils.{name}", run_name="__main__")
