#! /usr/bin/env python3
if __name__ == "__main__":
    import os
    path = os.path.abspath(os.path.dirname(__file__))

    import sys
    sys.path.append(path)

    import code
    code.InteractiveConsole().interact()