#! /bin/bash

declare -a arr=(
    "api"
    "afputils"
    "arcutils"
    "bemanishark"
    "binutils"
    "cardconvert"
    "dbutils"
    "frontend"
    "ifsutils"
    "iidxutils"
    "proxy"
    "psmap"
    "read"
    "replay"
    "responsegen"
    "scheduler"
    "services"
    "struct"
    "trafficgen"
    "twodxutils"
)

declare -a cmdline=()

for project in "${arr[@]}"
do
    cmdline+=('-m')
    cmdline+=("bemani.utils.$project")
done

for test in `find bemani/tests/ -name "test_*.py" | sed 's,.*/,,' | sed  's,\.py,,'`
do
    cmdline+=('-m')
    cmdline+=("bemani.tests.$test")
done

MYPYPATH=$(python -c "import os; print(os.path.realpath('.'))") mypy \
    "${cmdline[@]}" \
    --warn-redundant-casts \
    --warn-unused-ignores \
    --disallow-untyped-calls \
    --disallow-untyped-defs \
    --disallow-subclassing-any \
    --disallow-incomplete-defs \
    --no-implicit-optional \
    --no-strict-optional
