#! /usr/bin/env python3
if __name__ == "__main__":
    import os
    path = os.path.abspath(os.path.dirname(__file__))

    import sys
    sys.path.append(path)
    sys.argv = [
        sys.argv[0],
        "discover",
        "-s",
        os.path.join(path, "bemani/tests"),
        *sys.argv[1:],
    ]

    import runpy
    runpy.run_module("unittest", run_name="__main__")