"""Remove bad DanEvo charts from the DB.

Revision ID: 4fbae3d0cb31
Revises: f64d138962e0
Create Date: 2025-10-24 00:59:53.007135

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import text


# revision identifiers, used by Alembic.
revision = '4fbae3d0cb31'
down_revision = 'f64d138962e0'
branch_labels = None
depends_on = None


def upgrade():
    conn = op.get_bind()

    # Remove any attempts that were made on now-invalid charts.
    sql = "DELETE FROM score WHERE musicid IN (SELECT id FROM music WHERE game = 'danevo' AND chart = 5)"
    conn.execute(text(sql), {})

    sql = "DELETE FROM score_history WHERE musicid IN (SELECT id FROM music WHERE game = 'danevo' AND chart = 5)"
    conn.execute(text(sql), {})

    sql = "DELETE FROM music WHERE game = 'danevo' AND chart = 5"
    conn.execute(text(sql), {})


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
