"""Config for what info to pull from remote servers.

Revision ID: 5fb631197b27
Revises: 25e9f367b137
Create Date: 2018-03-20 21:38:34.023921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fb631197b27'
down_revision = '25e9f367b137'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('server', sa.Column('config', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('server', 'config')
    # ### end Alembic commands ###
