"""Rename extid table to refid.

Revision ID: 6e2ac7400610
Revises: 314f97567294
Create Date: 2017-04-20 22:51:16.284843

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = '6e2ac7400610'
down_revision = '314f97567294'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('extid', 'refid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('refid', 'extid')
    # ### end Alembic commands ###
