"""Add game version to PCBID settings.

Revision ID: 8666c2253770
Revises: 3308af0e619f
Create Date: 2017-08-19 12:05:36.923453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8666c2253770'
down_revision = '3308af0e619f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('machine', sa.Column('version', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('machine', 'version')
    # ### end Alembic commands ###
