"""Respect ability for other servers to have <= 64 character tokens.

Revision ID: b09f1e39c951
Revises: 0df7f3dc4d23
Create Date: 2018-01-31 15:42:15.013060

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b09f1e39c951'
down_revision = '0df7f3dc4d23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('server', 'token',
               existing_type=mysql.VARCHAR(length=36),
               type_=sa.String(length=64),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('server', 'token',
               existing_type=sa.String(length=64),
               type_=mysql.VARCHAR(length=36),
               existing_nullable=False)
    # ### end Alembic commands ###
