"""Drop category column, add general column to music.

Revision ID: f1fe9fce9ace
Revises: f35b7dbdb672
Create Date: 2017-02-02 22:27:26.633758

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f1fe9fce9ace'
down_revision = 'f35b7dbdb672'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('music', sa.Column('data', sa.JSON(), nullable=True))
    op.drop_column('music', 'category')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('music', sa.Column('category', mysql.VARCHAR(length=63), nullable=True))
    op.drop_column('music', 'data')
    # ### end Alembic commands ###
