"""Make points column nullable.

Revision ID: f270dd360519
Revises: ee447dd6bfa8
Create Date: 2017-03-06 20:33:58.380331

"""
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f270dd360519'
down_revision = 'ee447dd6bfa8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('score', 'points',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('score_history', 'points',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('score_history', 'points',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('score', 'points',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    # ### end Alembic commands ###
