"""Add index to music to speed up play count queries.

Revision ID: f35b7dbdb672
Revises: 437a91b37583
Create Date: 2017-01-17 23:43:20.525727

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = 'f35b7dbdb672'
down_revision = '437a91b37583'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_music_id'), 'music', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_music_id'), table_name='music')
    # ### end Alembic commands ###
