"""Add custom area string to arcade configuration.

Revision ID: f64d138962e0
Revises: 3433293952c5
Create Date: 2022-10-15 21:23:02.461661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f64d138962e0'
down_revision = '3433293952c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('arcade', sa.Column('area', sa.String(length=63), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('arcade', 'area')
    # ### end Alembic commands ###
